spring.application.name=mcp-gateway
# 1. Uygulamanın çalışacağı varsayılan Port (Değiştirmiyoruz)
server.port=8080

# 2. H2 In-Memory Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:h2:mem:mcpgatewaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Hibernate (JPA) Ayarı: Biz Java kodu yazdıkça tabloları otomatik güncelle/oluştur
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# 4. H2 Konsol Ayarı (Veritabanını tarayıcıdan görsel olarak izlemek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console